# Leave blank to use defaults
subsample:
    - 1
    - 1
    - 1
mask_scale: 3
bkg_sub: True
padding: 50
workers: 16
cellfinder_params:
  n_free_cpus: 0
  voxel_sizes: 
    - 2.0 # Z
    - 1.8 # X
    - 1.8 # Y
  soma_diameter: 9 # in microns
  ball_xy_size: 8
  ball_overlap_fraction: 0.6
  log_sigma_size: 0.1
  n_sds_above_mean_thresh: 2
  soma_spread_factor: 1.4
  max_cluster_size: 100000
  ball_z_size: 8