[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "aind_smartspim_segmentation"
description = "Identifies cell proposals from SmartSPIM datasets."
license = {text = "MIT"}
requires-python = ">=3.10"
authors = [
    {name = "Allen Institute for Neural Dynamics"}
]
classifiers = [
    "Programming Language :: Python :: 3"
]
readme = "README.md"
dynamic = ["version"]

dependencies = [
    'aind-large-scale-prediction==1.0.0',
    'numpy==1.26.4',
    'scikit-image==0.22.0',
    'matplotlib==3.8.2',
    'scipy==1.15.2',
    'cupy-cuda11x==13.4.0',
    'neuroglancer==2.40.1',
    'aind-data-schema==2.8.0',
    'aind-data-schema-models>=5.7.1,<6',
    'pynvml',
    'bokeh==2.4.2',
    'dask[distributed]==2024.4.1',
    'dask_memusage',
    'argschema==3.0.4',
    'natsort==8.2.0',
    'zarr==2.18.0',
    'pathos==0.3.4',
    'pyyaml',
    'awscli',
]

[project.optional-dependencies]
dev = [
    'black',
    'coverage',
    'flake8',
    'interrogate',
    'isort',
    'Sphinx',
    'pygit2',
    'furo'
]

[tool.setuptools.packages.find]
where = ["code"]

[tool.setuptools.dynamic]
version = {attr = "aind_smartspim_segmentation.__version__"}

[tool.black]
line-length = 101
target_version = ['py39']
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | build
    | dist
  )/
  | .gitignore
)
'''

[tool.coverage.run]
omit = ["*__init__*"]
source = ["aind_smartspim_segmentation", "tests"]

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]
fail_under = 50

[tool.isort]
line_length = 101
profile = "black"

[tool.interrogate]
exclude = ["setup.py", "docs", "build"]
fail-under = 100
