# Leave blank to use defaults
start_plane: 0
end_plane: -1
n_free_cpus: 2
voxel_sizes: 
  - 2 # Z
  - 1.8 # X
  - 1.8 # Y
soma_diameter: 9 # in microns
ball_xy_size: 8
ball_z_size: 9
ball_overlap_fraction: 0.6
log_sigma_size: 0.1
n_sds_above_mean_thresh: 5
soma_spread_factor: 1.4
max_cluster_size: 100000
ball_z_size: 8